import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { url } from "inspector";

const prompt = Prompt({
  subsets : ["thai","latin"],
  weight : ["100","200","300","400","500","600","700","800","900"],
});


export const metadata: Metadata = {
  title: "Food Tracker App",
  description: "Generated by Venus SAU",
  keywords : ["food","Tracker","อากหาร","สุขถาพ","health"],
  icons: "/vercel.svg",
};
authors: [{
  name: "Venus SAU",
  url: "https://venus.dev"
}]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`$ {prompt.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
